/* eslint-disable @typescript-eslint/no-explicit-any */
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { ASSISTANT_IDENTITY } from "@/lib/assistant-identity";
import { inferEmeryDomain, domainPrompt, domainMetadata } from "@/lib/emery-domain";
import { selectRelevantMemories, buildExecutiveFocus } from "@/lib/emery-intelligence";

type AttachmentInput={storagePath:string;fileName:string;mimeType:string;sizeBytes:number};
type ChatInput={message?:string;attachments?:AttachmentInput[]};
type ChatAttachment={id:string;fileName:string;mimeType:string;sizeBytes:number;url:string|null};
const safe=(v:unknown):Record<string,unknown>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};

async function mainConversation(db:any,userId:string){
 const {data}=await db.from("conversations").select("id, metadata").eq("user_id",userId).eq("channel","main").order("started_at",{ascending:false}).limit(1).maybeSingle();
 if(data)return data;
 const {data:created,error}=await db.from("conversations").insert({user_id:userId,channel:"main",title:"Emery",metadata:{primary:true}}).select("id, metadata").single(); if(error)throw error; return created;
}
async function history(db:any,userId:string,conversationId:string){const {data}=await db.from("conversation_messages").select("id,role,content,created_at").eq("user_id",userId).eq("conversation_id",conversationId).order("created_at",{ascending:false}).limit(24);return (data??[]).reverse().map((x:any)=>({id:x.id,role:x.role,text:x.content,createdAt:x.created_at}));}
async function sign(db:any,rows:any[]):Promise<ChatAttachment[]>{return Promise.all(rows.map(async r=>{const {data}=await db.storage.from("emery-attachments").createSignedUrl(r.storage_path,600);return{id:r.id,fileName:r.file_name,mimeType:r.mime_type,sizeBytes:Number(r.size_bytes??0),url:data?.signedUrl??null}}));}
async function actionContext(db:any,userId:string){const now=new Date().toISOString();const [t,p,m]=await Promise.all([db.from("tasks").select("id,title,details,status,priority,due_at,metadata,project_id").eq("user_id",userId).neq("status","completed").order("priority",{ascending:false}).limit(15),db.from("projects").select("id,name,description,status,priority,goal,next_action").eq("user_id",userId).eq("status","active").order("priority",{ascending:false}).limit(10),db.from("meetings").select("id,title,meeting_at,participants,metadata").eq("user_id",userId).gte("meeting_at",now).order("meeting_at",{ascending:true}).limit(10)]);return{tasks:t.data??[],projects:p.data??[],meetings:m.data??[]};}
function responseText(p:any){return typeof p.output_text==="string"?p.output_text.trim():(p.output??[]).flatMap((x:any)=>x.content??[]).filter((x:any)=>x.type==="output_text").map((x:any)=>x.text??"").join("").trim();}

export const sendEmeryMessage=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:ChatInput)=>{const message=String(input?.message??"").trim();const attachments=Array.isArray(input?.attachments)?input.attachments.slice(0,5):[];if(!message&&!attachments.length)throw new Error("Message or attachment is required");return{message,attachments};}).handler(async({data,context})=>{
 const apiKey=process.env["OPENAI_API_KEY"];if(!apiKey)return{error:"The AI service isn't configured yet."} as const;const db=context.supabase as any,userId=context.userId;const conversation=await mainConversation(db,userId);const route=inferEmeryDomain(data.message);
 const {data:userMessage,error:saveError}=await db.from("conversation_messages").insert({user_id:userId,conversation_id:conversation.id,role:"user",content:data.message}).select("id,created_at").single();if(saveError)return{error:"Couldn't save your message. Please try again."} as const;
 if(data.attachments.length){for(const a of data.attachments)if(!a.storagePath.startsWith(`${userId}/`))return{error:"One attachment doesn't belong to your account."} as const;await db.from("message_attachments").insert(data.attachments.map(a=>({user_id:userId,conversation_id:conversation.id,message_id:userMessage.id,storage_path:a.storagePath,file_name:a.fileName,mime_type:a.mimeType,size_bytes:a.sizeBytes})));}
 const recent=await history(db,userId,conversation.id);const [{data:profile},{data:memories},actions]=await Promise.all([db.from("profiles").select("display_name,assistant_name,timezone,profile_summary").eq("user_id",userId).maybeSingle(),db.from("memories").select("id,title,content,memory_type,importance,confidence,created_at,updated_at").eq("user_id",userId).order("importance",{ascending:false}).limit(100),actionContext(db,userId)]);
 const selected=selectRelevantMemories(memories??[],data.message,recent,{maxItems:14,maxCharacters:5200});const focus=buildExecutiveFocus(actions);const memoryBlock=selected.map((m:any)=>`- [${m.memory_type}] ${m.title?`${m.title}: `:""}${m.content}`).join("\n");
 const profileBlock=profile?`Name: ${profile.display_name??""}\nTimezone: ${profile.timezone??""}\nAbout: ${profile.profile_summary??""}`:"";const actionBlock=JSON.stringify(actions).slice(0,8500);
 const attachmentRows=data.attachments.length?await db.from("message_attachments").select("id,storage_path,file_name,mime_type,size_bytes").eq("user_id",userId).eq("message_id",userMessage.id):{data:[]};const signed=await sign(db,attachmentRows.data??[]);const userContent:any[]=[{type:"input_text",text:data.message||"Please review the attachment."}];for(const a of signed){if(!a.url)continue;userContent.push(a.mimeType.startsWith("image/")?{type:"input_image",image_url:a.url}:{type:"input_file",file_url:a.url});}
 const previous=recent.filter((x:any)=>x.id!==userMessage.id).slice(-18);const resp=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",input:[{role:"system",content:ASSISTANT_IDENTITY+`\n\nDOMAIN ROUTING:\n${route.domain.toUpperCase()} (${route.reason}). ${domainPrompt(route)}\nThis routing changes data context only, never Emery's identity.\n\nPERMISSION: Do not claim a structured write unless a tool/control layer confirms it. Casual mentions are not permission to create tasks/projects/meetings.`},...(profileBlock?[{role:"system",content:`CORE PROFILE:\n${profileBlock}`}]:[]),...(memoryBlock?[{role:"system",content:`SELECTED LONG-TERM MEMORY:\n${memoryBlock}`}]:[]),{role:"system",content:`CURRENT ACTIVE OS CONTEXT (bounded):\n${actionBlock}\n\nQUIET FOCUS:\n${focus}\nUse only when relevant. Favor one highest-value next action; never dump a dashboard.`},...previous.map((x:any)=>({role:x.role,content:[{type:x.role==="assistant"?"output_text":"input_text",text:x.text}]})),{role:"user",content:userContent}]})});if(!resp.ok)return{error:"Emery couldn't answer right now. Please try again."} as const;const reply=responseText(await resp.json());if(!reply)return{error:"Emery returned an empty response."} as const;const {data:assistantMessage}=await db.from("conversation_messages").insert({user_id:userId,conversation_id:conversation.id,role:"assistant",content:reply}).select("id,created_at").single();
 await db.from("conversations").update({metadata:{...safe(conversation.metadata),last_domain:route.domain,identity:"central-v1"},updated_at:new Date().toISOString()}).eq("id",conversation.id).eq("user_id",userId);
 return{reply,conversationId:conversation.id,userMessage:{id:userMessage.id,role:"user" as const,text:data.message,createdAt:userMessage.created_at,attachments:signed},assistantMessage:assistantMessage?{id:assistantMessage.id,role:"assistant" as const,text:reply,createdAt:assistantMessage.created_at,attachments:[] as ChatAttachment[]}:null} as const;
});

export const getMainConversation=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const db=context.supabase as any,c=await mainConversation(db,context.userId);const {data}=await db.from("conversation_messages").select("id,role,content,created_at").eq("user_id",context.userId).eq("conversation_id",c.id).order("created_at",{ascending:true}).limit(500);return{conversationId:c.id,messages:(data??[]).map((x:any)=>({id:x.id,role:x.role,text:x.content,createdAt:x.created_at,attachments:[]}))};});
export const getMainConversationPage=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).inputValidator((i:{before?:string|null;limit?:number}={})=>({before:i.before??null,limit:Math.min(100,Math.max(20,Number(i.limit??80)))})).handler(async({data,context})=>{const db=context.supabase as any,c=await mainConversation(db,context.userId);let q=db.from("conversation_messages").select("id,role,content,created_at").eq("user_id",context.userId).eq("conversation_id",c.id).order("created_at",{ascending:false}).limit(data.limit+1);if(data.before)q=q.lt("created_at",data.before);const {data:rows}=await q;const page=(rows??[]).slice(0,data.limit).reverse();return{conversationId:c.id,messages:page.map((x:any)=>({id:x.id,role:x.role,text:x.content,createdAt:x.created_at,attachments:[]})),hasMore:(rows??[]).length>data.limit,nextBefore:page[0]?.created_at??null};});

export const listTasks=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const {data,error}=await (context.supabase as any).from("tasks").select("*").eq("user_id",context.userId).order("priority",{ascending:false});if(error)throw error;return{tasks:data??[]};});
export const createTask=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:{title:string;details?:string;dueAt?:string|null;priority?:number})=>({title:String(i.title).trim(),details:i.details?.trim()||null,dueAt:i.dueAt||null,priority:Math.min(5,Math.max(1,Number(i.priority??3)))})).handler(async({data,context})=>{const {data:t,error}=await (context.supabase as any).from("tasks").insert({user_id:context.userId,title:data.title,details:data.details,due_at:data.dueAt,priority:data.priority,status:"inbox",source_type:"manual",metadata:domainMetadata("general")}).select("id").single();if(error)throw error;return{id:t.id};});
export const setTaskCompleted=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:{id:string;completed:boolean})=>({id:String(i.id),completed:Boolean(i.completed)})).handler(async({data,context})=>{const {error}=await (context.supabase as any).from("tasks").update({status:data.completed?"completed":"inbox",completed_at:data.completed?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",data.id).eq("user_id",context.userId);if(error)throw error;return{ok:true};});
export const listProjects=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const {data,error}=await (context.supabase as any).from("projects").select("*").eq("user_id",context.userId).order("priority",{ascending:false});if(error)throw error;return{projects:data??[]};});
export const saveProject=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:{id?:string;name:string;description?:string;status?:string;priority?:number;goal?:string;nextAction?:string})=>({...i,name:String(i.name).trim(),priority:Math.min(5,Math.max(1,Number(i.priority??3)))})).handler(async({data,context})=>{const db=context.supabase as any,payload={name:data.name,description:data.description?.trim()||null,status:data.status||"active",priority:data.priority,goal:data.goal?.trim()||null,next_action:data.nextAction?.trim()||null};if(data.id){const {error}=await db.from("projects").update({...payload,updated_at:new Date().toISOString()}).eq("id",data.id).eq("user_id",context.userId);if(error)throw error;return{id:data.id};}const {data:p,error}=await db.from("projects").insert({user_id:context.userId,...payload}).select("id").single();if(error)throw error;return{id:p.id};});
export const listMeetings=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const {data,error}=await (context.supabase as any).from("meetings").select("*").eq("user_id",context.userId).order("meeting_at",{ascending:true});if(error)throw error;return{meetings:data??[]};});
export const createMeeting=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:{title:string;meetingAt:string;participants?:string[]})=>({title:String(i.title).trim(),meetingAt:i.meetingAt,participants:i.participants??[]})).handler(async({data,context})=>{const {data:m,error}=await (context.supabase as any).from("meetings").insert({user_id:context.userId,title:data.title,meeting_at:data.meetingAt,participants:data.participants,metadata:{source_type:"manual",...domainMetadata("general")}}).select("id").single();if(error)throw error;return{id:m.id};});
